#!/bin/bash
set -euo pipefail

echo "Commmand: ansible -i \"localhost,\" all  -m debug  -a 'msg=\"{{ $1 }}\"'  --ask-vault-password -e@$2"

ansible -i "localhost," all  -m debug  -a 'msg="{{ '$1' }}"'  --ask-vault-password -e@$2

if [[ $? != 0 ]]; then
    echo "Example: ansible-vault-var <var_name> <yaml_file_path>"
fi
